--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/senpayeh/StaffToolsMCPE
branches:
- master
projects:
  StaffToolsMCPE:
    path: ""
    libs: 
    - src: muqsit/InvMenu/InvMenu
      version: ^2.1.0
...
