---
name: StaffTools
author: Senpayeh
main: senpayeh\stafftools\StaffTools
version: 2.0.0
api: 3.0.0
description: Simple plugin to help you detecting cheaters
commands:
  tools:
    description: Get the compass for the ToolsGUI
permissions:
  staffmode.command:
    default: op
    description: Permission to use /tools
  staffmode.warnmessage:
    default: op
    description: Allow staff members to get the warning messages
...