---
name: StaffTools
author: Senpayeh
main: Senpayeh\StaffTools\Main
version: 1.0
api: [3.0.0]
description: Advanced plugin to detect cheaters in your server
depend: [Alias]
commands:
  tools:
    description: Toggle StaffTools menu
  lol:
    description: a
permissions:
  tools.command:
    default: op
    description: Use /tools command
...
